//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTuTransporte
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camiones()
        {
            this.Choferes = new HashSet<Choferes>();
        }
    
        public int Id { get; set; }
        public string Serie { get; set; }
        public string Matricula { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> FK_Rutas { get; set; }
    
        public virtual Denuncias Denuncias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Choferes> Choferes { get; set; }
    }
}
